### ISSUE TITLE
Error processing data parameters: Unrecognized field when generating print logs report

### ISSUE THREAD

**Issue by matthewsmith-commits** [PaperCutSoftware/PaperCutExamples#19] opened 2020-11-05 23:08 UTC
This works correctly on PaperCut v19.1, but on v20, calling proxy.api.generateAdHocReport with parameters causes an error.

For example, the following bit of code works correctly in version 19.1 :

import os

from datetime import date, timedelta, datetime
from dateutil.relativedelta import *

import xmlrpc.client
import json
from ssl import create_default_context, Purpose

auth_token = 'password'
host="https://localhost:9192/rpc/api/xmlrpc"
proxy = xmlrpc.client.ServerProxy(host, verbose=False, context = create_default_context(Purpose.CLIENT_AUTH))

from datetime import date, timedelta, datetime
from dateutil.relativedelta import *

from_date = (datetime.now() - relativedelta(months=1)).strftime('%Y-%m-%dT%H:%M')
to_date = datetime.now().strftime('%Y-%m-%dT%H:%M')

data = {
				"from-date":from_date,
				"to-date":to_date,
				"allocated-account-type": "SHARED",
				"cancelled":"NOT_CANCELLED",
				"printed": "ANY",
				"show-filters-in-header": True
				}
				
proxy.api.generateAdHocReport(auth_token,
								"print_logs",
								json.dumps(data),
								"CSV",
								"Integration",
								os.getcwd())

However, the same code will produce an error when you are running PaperCut v20 or higher. If no parameters are passed (data = {}), it will generate the report correctly. I've included the traceback below. 

Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "C:\Users\matthew.smith\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\matthew.smith\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Users\matthew.smith\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\matthew.smith\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "C:\Users\matthew.smith\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1342, in parse_response
    return u.close()
  File "C:\Users\matthew.smith\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 327: 'java.lang.Exception: Error processing data parameters: Unrecognized field "from-date" (Class biz.papercut.pcng.reports.DataParamsJsonObject), not marked as ignorable\n at [Source: java.io.StringReader@1061bd9d; line: 1, column: 16] (through reference chain: biz.papercut.pcng.reports.DataParamsJsonObject["from-date"])'>

**Comment by alecthegeek** [comment] 2020-11-06 03:08
@matthewsmith-commits  Can be specific about which version of 20.0 you are running please.

**Comment by matthewsmith-commits** [comment] 2020-11-06 15:35
@alecthegeek I did some more testing and it appears this problem began with 20.0.3 (Build 55021 2020-08-13). 
I got the expected output with the following builds:
20.0.0 (Build 54402 2020-05-13)
20.0.1 (Build 54657 2020-06-16)
20.0.2 (Build 54736 2020-06-30)

I tested and received the unrecognized field error with these builds:
20.0.3 (Build 55021 2020-08-13)
20.0.4 (Build 55447 2020-09-30)
20.1.0.55643

**Comment by alecthegeek** [comment] 2020-11-07 02:18
Thank you for being so thorough.

I've escalated in an internal ticket to our dev team (FYI: It's ticket #1027794)

**Comment by RyanReichenberg** [comment] 2020-11-10 00:07
Hi @matthewsmith-commits,

Out of curiosity, if hardcode dates:
```
"from-date":"2019-03-01T09:30",
"to-date":"2019-06-01T09:30",
```
from the payload, does it work as intended?

**Comment by matthewsmith-commits** [comment] 2020-11-10 15:46
@RyanReichenberg 

Hard coding the date also fails. If the date was improperly formatted, it would result in a different error, like below:

xmlrpc.client.Fault: <Fault 327: 'java.lang.Exception: Error processing data parameters: Can not deserialize value of type java.util.Date from String "2019-03-01T": not a valid representation (error: Failed to parse Date value \'2019-03-01T\': Unparseable date: "2019-03-01T")\n at [Source: {"from-date": "2019-03-01T", "to-date": "2020-11-101T", "allocated-account-type": "SHARED", "cancelled": "NOT_CANCELLED", "printed": "ANY", "show-filters-in-header": true}; line: 1, column: 15] (through reference chain: biz.papercut.pcng.reports.DataParamsJsonObject["from-date"])'>

I am getting the Unrecognized field error on PaperCut 20.0.3 and above when trying to specify other parameters to the print_logs report. Same error for allocated-account-type, cancelled, printed, and show-filters-in-header.

**Comment by RyanReichenberg** [comment] 2020-11-10 23:20
Thanks for the info!

I think we have a developer looking into this.

**Comment by RyanReichenberg** [comment] 2020-11-11 00:07
@matthewsmith-commits 

I come with hat in hand. 
Internally, we manage two versions of a JSON library for compatibility reasons. It appears that at some point in time, libraries were swapped and it looks like it is causing the problems here. A fix for this should be out in the next maintenance release. 

I'll be in touch with a bug ticket number so you can track the fix in our release notes.

**Comment by RyanReichenberg** [comment] 2020-11-24 23:11
@matthewsmith-commits 
Sorry for the delay in getting back to you! I can confirm this should be out in 20.1.2. The  ticket number for this one is: PC-17818

**Comment by alecthegeek** [comment] 2020-12-08 20:49
I will close this issue. If 20.1.2 does not address the issue we can reopen.

**Closed by alecthegeek** 2020-12-08 20:49 UTC
